### ISSUE TITLE
Timeout error occurs

### ISSUE THREAD

**Issue by BaruchDavid** [toyokazu/fluent-plugin-mqtt-io#17]
Hello, i'am trying to send some messages to the queue, but i get timeout error.
Here is log: 

> 2020-04-30 13:54:20 +0200 [debug]: #0 start to connect mqtt broker mqbroker-dev-test.comp.de:8883
> 2020-04-30 13:54:20 +0200 [debug]: #0 fluent/log.rb:302:debug: tailing paths: target = C:\\data\log\app.log | existing =
> 2020-04-30 13:54:20 +0200 [info]: #0 fluent/log.rb:322:info: following tail of C:\\data\log\app.log
> 2020-04-30 13:54:20 +0200 [debug]: #0 publish_event_stream: Fluent::MultiEventStream
> 2020-04-30 13:54:20 +0200 [debug]: #0 MqttOutput::block (2 levels) in publish_event_stream: out_queue, 1588247660, {"message"=>"2020-04-30T13:49:37,021 | DEBUG | Thread-56| ForwardQueue|  | 
> 									Periodic wake-up of queue for class org.osgi.service.event.Event"}
> 2020-04-30 13:54:20 +0200 [warn]: #0 fluent/log.rb:342:warn: emit transaction failed: 
> 								error_class=Fluent::Plugin::MqttProxy::MqttError 
> 								error="MQTT not connected exception occurs in out_mqtt." 
> 								location="C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mqtt-io-0.4.4/lib/fluent/plugin/mqtt_proxy.rb:150:in 
> 								`rescue in rescue_disconnection'" tag="out_queue"
> 
> 2020-04-30 13:54:20 +0200 [info]: #0 fluent/log.rb:322:info: fluentd worker is now running worker=0
> 2020-04-30 13:54:25 +0200 [error]: #0 Timeout error occurs in out_mqtt.,Timeout::Error,execution expired
> 2020-04-30 13:54:25 +0200 [error]: #0 Retry in 1 sec
> 2020-04-30 13:54:26 +0200 [debug]: #0 connected to mqtt broker mqbroker-dev-test.comp.de:8883 for out_mqtt
> 2020-04-30 13:54:37 +0200 [debug]: #0 publish_event_stream: Fluent::MultiEventStream
> 2020-04-30 13:54:37 +0200 [debug]: #0 MqttOutput::block (2 levels) in publish_event_stream: out_queue, 1588247677, {"message"=>"2020-04-30T13:54:37,034 | DEBUG | Thread-56| ForwardQueue|  | 
> 									Periodic wake-up of queue for class org.osgi.service.event.Event"}
> 2020-04-30 13:54:42 +0200 [error]: #0 Timeout error occurs in out_mqtt.,Timeout::Error,execution expired
> 2020-04-30 13:54:42 +0200 [error]: #0 Retry in 1 sec

Here is my out-config:

> <source>
>   @type tail
>   path C:\ta\karaf\data\log\karaf.log
>   pos_file C:\ta\karaf\data\log\karaf.log.pos
>   read_from_head true	
>   tag out_queue
>   rotate_wait 5
>   <parse>
>     @type none
>   </parse>
> </source>
> 
> <match out_queue>
>    @type mqtt
>    @log_level debug
>    host 'mqbroker-dev-test.comp.de'
>    port '8883'	
>      topic "test"
>      <security>
>        use_tls false
>        username 'secret'
>        password 'secret'
>      </security>
>      <format>
>        @type json
>        add_newline false
>      </format>
>  </match>

What should i do?

**Comment by toyokazu** [comment]
Sorry for being late reply. I hope that your issue has already been solved.
